import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <ul style={{ display: "flex", margin: "0px 10px" }}>
            <Link href={"/"}>
              <li style={{ margin: "0px 10px" }}>Home</li>
            </Link>
            <Link href={"/about"}>
              <li style={{ margin: "0px 10px" }}>About</li>
            </Link>
            <Link href={"/blogs"}>
              <li style={{ margin: "0px 10px" }}>Blogs</li>
            </Link>

            <Link href={"/posts"}>
              <li style={{ margin: "0px 10px" }}>Posts</li>
            </Link>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
